---
name: "Release"

on:
  push:
    branches:
      - "master"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Generate ~/.m2/settings.xml
        uses: whelk-io/maven-settings-xml-action@v14
        with:
          servers: '[{ "id": "github", "username": "${{ github.actor }}", "password": "${{ secrets.GITHUB_TOKEN }}" }]'

      - name: Publish Release
        run: mvn clean package de.jutzig:github-release-plugin:release
